User settings
YkeSmit1/TOSR pull request #56
Opened 2021-01-23 16:09 UTC by eddovandenboom

Implemented user settings: useSolver (saves whether useSolver is selected), pbnFilePath (saves location of current pbn file) and boardNumber (saves current board number). When the application starts, the saved settings are loaded.

2021-01-23 21:33 UTC, YkeSmit1 requested changes

2021-01-23 21:33 UTC, YkeSmit1 commented on Tosr/Form1.cs
> +                boardNumber = Settings.Default.boardNumber;
There is a chance boardnumber is larger then the highest number in the Pnb file. For example, if it is overwritten by a third party application. So please check for this.

2021-01-23 21:33 UTC, YkeSmit1 commented on Tosr/Form1.cs
> +                Settings.Default.pbnFilePath = "";
I think we should also save the pbnFilePath in the form close. To make it consistent. There should be only one place to store all the settings. To achieve this, you need to change the variable PbnFilename to PbnFilepath. And only save it if the file exists. That would make the most sense to the user.

2021-01-25 20:20 UTC, eddovandenboom commented on Tosr/Form1.cs
> +                boardNumber = Settings.Default.boardNumber;
I check this now in the method LoadCurrentBoard: if the board number doesn't exist, then I set it equal to 1

2021-01-25 20:20 UTC, eddovandenboom commented on Tosr/Form1.cs
> +                boardNumber = Settings.Default.boardNumber;
I check this now in the method LoadCurrentBoard: if the board number doesn't exist, then I set it equal to 1

2021-01-26 00:01 UTC, YkeSmit1 approved these changes

2021-01-26 00:02 UTC, merged