Bidding parameters in file
YkeSmit1/TOSR pull request #60
Opened 2021-01-28 01:41 UTC by eddovandenboom

Issue #44

2021-01-31 20:03 UTC, YkeSmit1 requested changes

2021-01-31 20:03 UTC, YkeSmit1 commented on Tosr/Form1.cs
> +            // System parameters
Suggestion, split up system and optimization parameter saving and use the flow
if (path not empty)
  try
  BidManager.SetParemeter
  return
except
{
 Show error
}
LoadDefaultParameters from resource

2021-01-31 20:03 UTC, YkeSmit1 commented on Tosr/Form1.resx
> -        YQUAAAAJcEhZcwAAFiUAABYlAUlSJPAAAACRSURBVDhPY/j27dt/SjDYACcnJ7IwigEf3n8kCZNswPNb
Also not part of the issue. Revert

2021-01-31 20:03 UTC, YkeSmit1 commented on Tosr/Properties/Settings.settings
> +    <Setting Name="systemParametersPath" Type="System.String" Scope="User">
Shouldn't the default be an empty string? Since we are using resource now

2021-01-31 21:08 UTC, YkeSmit1 commented on SystemParameters.json
> +{
Can you create a unittest which bids with two sets of parameters. To prove that different sets of parameters are used

2021-02-02 19:11 UTC, eddovandenboom commented on SystemParameters.json
> +        {"Item1": {
I solved this using a custom deserializer

2021-02-05 01:01 UTC, eddovandenboom commented on SystemParameters.json
> +{
I added unit tests as well as integration tests

2021-02-05 13:44 UTC, YkeSmit1 reviewed
a Few small changes

2021-02-05 13:44 UTC, YkeSmit1 commented on Common/Util.cs
> +            Stream stream = Assembly.GetCallingAssembly().GetManifestResourceStream($"{projectName}.{fileName}");
Stream en StreamReader should use a using clause. Otherwise unmanaged resources will not be freed immediately.

2021-02-05 13:44 UTC, YkeSmit1 commented on Tosr/Form1.cs
> +        private void useSavedSystemParameters()
Please use camelcase (UseSavedParameterFiles) and also below

2021-02-05 13:44 UTC, YkeSmit1 commented on Tosr/Form1.cs
> +            if (!String.IsNullOrEmpty(Settings.Default.systemParametersPath))
I prefere string.IsNullOrWhiteSpace. Because spaces and EOL also don't qualify

2021-02-06 23:53 UTC, YkeSmit1 approved these changes

2021-02-07 00:19 UTC, merged