Experimental way to get north bid
YkeSmit1/TOSR pull request #71
Opened 2021-03-19 22:23 UTC by YkeSmit1

2021-04-05 13:15 UTC, eddovandenboom requested changes

2021-04-05 13:15 UTC, eddovandenboom commented on Tosr/BidManager.cs
> +            var dictionary = tricksForBid.ToDictionary((key => key.Key), (value => (value.Value, GetBidPosibility(value.Key, biddingState.CurrentBid))));
Here I also find the naming confusing, with key.Key, value.Value and value.Key. What keys and values are being referred to? Explicit names would greatly improve readability in my view.

2021-04-05 17:26 UTC, YkeSmit1 commented on Tosr/BiddingInformation.cs
> +                new Fase[] { Fase.ScanningControls }).Count();
Good suggestion. Done

2021-04-05 17:26 UTC, YkeSmit1 commented on Tosr/BidManager.cs
> +        bool useSingleDummySolverDuringRelaying = false;
Done

2021-04-05 18:18 UTC, YkeSmit1 commented on Tosr/BidManager.cs
> +                }
I cannot use something else then Key and Value. These are properties of KeyValuePair of the dictionary. Not tuples. About g and x, x is compound and cannot be named better. g is the usual way to name a grouping. I will not change it

2021-04-05 18:28 UTC, YkeSmit1 commented on Tosr/BidManager.cs
> +            var dictionary = tricksForBid.ToDictionary((key => key.Key), (value => (value.Value, GetBidPosibility(value.Key, biddingState.CurrentBid))));
I renamed it to keyValuePair because it it a more descriptive name. I also remove parenthesis.

2021-04-05 18:30 UTC, YkeSmit1 commented on Tosr/BidManager.cs
> +                    1 => UpdateAndLog(reachableContracts.Single().Key),
It does. I thought about removing it, but I thought this code was more readable. And the case for more then one contract, might also change in the future.

2021-04-10 14:23 UTC, eddovandenboom approved these changes

2021-04-27 11:42 UTC, YkeSmit1 commented
PR approved by Eddo

2021-04-27 11:42 UTC, merged